from pathlib import Path

from plotter_processor.centerline_font.models import (
    CenterlineGlyph,
    CenterlineStroke,
    CompiledCenterlineFont,
)
from plotter_processor.centerline_font.serializer import write_centerline_font_atomic
from plotter_processor.fast_font import FastFont
from plotter_processor.fast_layout import FastLayoutConfig
from plotter_processor.fast_pipeline import run_fast_pipeline
from plotter_processor.models import Point


def test_fast_pipeline_writes_combined_multipage_gcode(tmp_path: Path) -> None:
    cache = tmp_path / "font-cache.json"
    glyph = CenterlineGlyph(
        "а", ord("а"), "a", 500,
        (CenterlineStroke(0, (Point(0, 0), Point(400, 500)), False),),
    )
    write_centerline_font_atomic(
        CompiledCenterlineFont(Path("font.ttf"), "f" * 64, 1000, 800, -200, 0, {"а": glyph}),
        cache,
        config={},
    )
    input_path = tmp_path / "input.md"
    input_path.write_text("а а а а а а", encoding="utf-8")
    FastFont.clear_cache()

    result = run_fast_pipeline(
        input_path,
        cache,
        tmp_path / "output",
        layout_config=FastLayoutConfig(
            page_width_mm=3,
            page_height_mm=10,
            margin_left_mm=1,
            margin_right_mm=1,
            margin_top_mm=1,
            margin_bottom_mm=1,
            font_size_mm=2,
            line_height_mm=3,
            word_spacing_mm=1,
        ),
    )

    assert result.pages > 1
    assert result.gcode_path == tmp_path / "output" / "output.gcode"
    gcode = result.gcode_path.read_text(encoding="utf-8")
    assert gcode.count("; Generated by plotter-processor") == 1
    assert gcode.count("; End") == 1
    for number in range(1, result.pages + 1):
        assert f"; ===== PAGE {number}/{result.pages} START =====" in gcode
        assert not (tmp_path / "output" / f"page-{number:03d}.gcode").exists()
