from pathlib import Path

import pytest

from plotter_processor.gcode_exporter import (
    generate_calibration_gcode,
    generate_gcode,
    transform_point,
    write_gcode_atomic,
)
from plotter_processor.models import PathDocument, PlotterStroke, Point
from plotter_processor.motion_config import resolve_motion_profile


@pytest.fixture
def path_document() -> PathDocument:
    return PathDocument(
        page_width_mm=100.0,
        page_height_mm=100.0,
        strokes=[
            PlotterStroke(
                id=0,
                points=[Point(10.0, 20.0), Point(20.0, 30.0), Point(30.0, 40.0)],
                closed=False,
            )
        ],
        warnings=[],
    )


@pytest.fixture
def machine_config() -> dict[str, object]:
    return {
        "page_origin_mm": {"x": 5.0, "y": 10.0},
        "axes": {"invert_x": False, "invert_y": True},
        "pen": {"up_z_mm": 5.0, "down_z_mm": 1.0, "settle_ms": 100},
        "feedrate_mm_min": {"draw": 1000, "travel": 3000, "z": 500},
        "workspace_mm": {"min_x": 0, "max_x": 220, "min_y": 0, "max_y": 220},
        "gcode": {
            "home": False,
            "absolute_positioning": True,
            "units_mm": True,
            "decimals": 3,
        },
    }


def test_transforms_origin_and_inverted_y(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    transformed = transform_point(Point(10.0, 20.0), path_document, machine_config)

    assert transformed == Point(15.0, 90.0)


def test_generates_safe_header_without_home(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    gcode = generate_gcode(path_document, machine_config)

    assert "G21\n" in gcode
    assert "G90\n" in gcode
    assert "G28" not in gcode
    assert gcode.startswith("; Generated by plotter-processor\n")


def test_metadata_comments_do_not_change_gcode_motion_commands(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    regenerated = generate_gcode(path_document, machine_config)
    full_run = generate_gcode(
        path_document,
        machine_config,
        motion_profile=resolve_motion_profile(machine_config),
        motion={"ideal_total_time_seconds": 12.5},
    ).replace(
        "; Generated by plotter-processor\n",
        "; Generated by plotter-processor\n; Page 1/1\n",
        1,
    )

    commands = lambda value: [
        line for line in value.splitlines() if line and not line.startswith(";")
    ]
    assert commands(regenerated) == commands(full_run)
    assert regenerated != full_run


def test_lifts_pen_before_travel_and_formats_coordinates(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    lines = generate_gcode(path_document, machine_config).splitlines()
    travel_index = lines.index("G0 X15.000 Y90.000 F3000.000")

    assert lines[travel_index - 1] == "G0 Z5.000 F500.000"
    assert lines[travel_index + 1] == "G1 Z1.000 F500.000"
    assert "G1 X25.000 Y80.000 F1000.000" in lines
    assert "G1 X35.000 Y70.000" in lines


def test_rejects_invalid_pen_z(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    machine_config["pen"]["up_z_mm"] = 1.0  # type: ignore[index]

    with pytest.raises(ValueError, match="must be greater"):
        generate_gcode(path_document, machine_config)


def test_rejects_workspace_violation(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    machine_config["workspace_mm"]["max_x"] = 20.0  # type: ignore[index]

    with pytest.raises(ValueError, match="outside workspace"):
        generate_gcode(path_document, machine_config)


def test_rejects_non_finite_point(machine_config: dict[str, object]) -> None:
    document = PathDocument(
        page_width_mm=100,
        page_height_mm=100,
        strokes=[PlotterStroke(id=0, points=[Point(1, 1), Point(float("nan"), 2)], closed=False)],
        warnings=[],
    )

    with pytest.raises(ValueError, match="finite"):
        generate_gcode(document, machine_config)


def test_enforces_command_limit(
    path_document: PathDocument, machine_config: dict[str, object]
) -> None:
    with pytest.raises(ValueError, match="safe limit"):
        generate_gcode(path_document, machine_config, max_commands=2)


def test_writes_gcode_atomically(tmp_path: Path) -> None:
    output = tmp_path / "output.gcode"

    write_gcode_atomic("G21\n; End\n", output)

    assert output.read_text(encoding="utf-8") == "G21\n; End\n"
    assert list(tmp_path.glob("*.tmp")) == []


def test_calibration_checks_corners_and_draws_small_square(
    machine_config: dict[str, object],
) -> None:
    gcode = generate_calibration_gcode("A5", machine_config)

    assert "; Pen-up corner check" in gcode
    assert gcode.count(" F3000.000") >= 5
    assert "G1 Z1.000 F500.000" in gcode
    assert "G28" not in gcode


def test_calibration_does_not_draw_full_frame_without_flag(
    machine_config: dict[str, object],
) -> None:
    normal = generate_calibration_gcode("A5", machine_config)
    full_frame = generate_calibration_gcode("A5", machine_config, full_page_frame=True)

    assert full_frame.count("G1 X") > normal.count("G1 X")


def test_calibration_rejects_page_outside_workspace(
    machine_config: dict[str, object],
) -> None:
    with pytest.raises(ValueError, match="outside workspace"):
        generate_calibration_gcode("A4", machine_config)
