import math
import os
import tempfile
from pathlib import Path
from typing import Any

from plotter_processor.models import PathDocument, Point, Stroke
from plotter_processor.page_renderer import PAGE_SIZES_MM

DEFAULT_MAX_GCODE_COMMANDS = 1_000_000


def transform_point(
    point: Point,
    document: PathDocument,
    machine_config: dict[str, Any],
) -> Point:
    origin = _mapping(machine_config, "page_origin_mm")
    axes = _mapping(machine_config, "axes")
    page_x = document.page_width_mm - point.x if axes.get("invert_x", False) else point.x
    page_y = document.page_height_mm - point.y if axes.get("invert_y", False) else point.y
    return Point(
        x=_number(origin, "x") + page_x,
        y=_number(origin, "y") + page_y,
    )


def generate_gcode(
    document: PathDocument,
    machine_config: dict[str, Any],
    *,
    max_commands: int = DEFAULT_MAX_GCODE_COMMANDS,
) -> str:
    settings = _validated_settings(document, machine_config)
    if max_commands < 1:
        raise ValueError("max_commands must be positive")

    decimals = settings["decimals"]
    z_feed = _format_number(settings["z_feed"], decimals)
    up_z = _format_number(settings["up_z"], decimals)
    down_z = _format_number(settings["down_z"], decimals)
    travel_feed = _format_number(settings["travel_feed"], decimals)
    draw_feed = _format_number(settings["draw_feed"], decimals)

    lines = ["; Generated by plotter-processor"]
    if settings["units_mm"]:
        lines.append("G21")
    if settings["absolute_positioning"]:
        lines.append("G90")
    if settings["home"]:
        lines.append("G28")
    lines.append(f"G0 Z{up_z} F{z_feed}")

    for stroke in document.strokes:
        source_points = [stroke.points[0]]
        for point in stroke.points[1:]:
            if point != source_points[-1]:
                source_points.append(point)
        machine_points = [
            transform_point(point, document, machine_config) for point in source_points
        ]
        _validate_workspace(machine_points, settings["workspace"])
        start = machine_points[0]
        travel_command = (
            f"G0 X{_format_number(start.x, decimals)} "
            f"Y{_format_number(start.y, decimals)} F{travel_feed}"
        )
        _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
        lines.extend((travel_command, f"G1 Z{down_z} F{z_feed}", f"G4 P{settings['settle_ms']}"))
        draw_points = list(machine_points[1:])
        if getattr(stroke, "closed", False) and machine_points[-1] != machine_points[0]:
            draw_points.append(machine_points[0])
        for index, point in enumerate(draw_points):
            feed = f" F{draw_feed}" if index == 0 else ""
            lines.append(
                f"G1 X{_format_number(point.x, decimals)} "
                f"Y{_format_number(point.y, decimals)}{feed}"
            )
        _append_unique(lines, f"G0 Z{up_z} F{z_feed}")

    _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
    lines.extend(("M400", "M84", "; End"))
    if len(lines) > max_commands:
        raise ValueError(
            f"G-code would contain {len(lines)} commands, exceeding the safe limit "
            f"of {max_commands}."
        )
    return "\n".join(lines) + "\n"


def write_gcode_atomic(gcode: str, output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(gcode)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_path = Path(temporary.name)
        temporary_path.replace(path)
    except Exception:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise


def generate_calibration_gcode(
    page: str,
    machine_config: dict[str, Any],
    *,
    full_page_frame: bool = False,
) -> str:
    if page not in PAGE_SIZES_MM:
        raise ValueError(f"Unsupported page size: {page}")
    page_width, page_height = PAGE_SIZES_MM[page]
    inset = 10.0
    corners = [
        Point(inset, inset),
        Point(page_width - inset, inset),
        Point(page_width - inset, page_height - inset),
        Point(inset, page_height - inset),
    ]
    square_origin = Point(inset * 2, inset * 2)
    square = [
        square_origin,
        Point(square_origin.x + 20.0, square_origin.y),
        Point(square_origin.x + 20.0, square_origin.y + 20.0),
        Point(square_origin.x, square_origin.y + 20.0),
        square_origin,
    ]
    drawing_strokes = [Stroke(points=square, source_component=0)]
    if full_page_frame:
        drawing_strokes.insert(
            0,
            Stroke(points=[*corners, corners[0]], source_component=0),
        )
    document = PathDocument(
        page_width_mm=page_width,
        page_height_mm=page_height,
        strokes=drawing_strokes,
        warnings=[],
    )
    settings = _validated_settings(document, machine_config)
    machine_corners = [transform_point(point, document, machine_config) for point in corners]
    _validate_workspace(machine_corners, settings["workspace"])

    decimals = settings["decimals"]
    up_z = _format_number(settings["up_z"], decimals)
    z_feed = _format_number(settings["z_feed"], decimals)
    travel_feed = _format_number(settings["travel_feed"], decimals)
    header = ["; Calibration generated by plotter-processor"]
    if settings["units_mm"]:
        header.append("G21")
    if settings["absolute_positioning"]:
        header.append("G90")
    if settings["home"]:
        header.append("G28")
    header.append(f"G0 Z{up_z} F{z_feed}")
    header.append("; Pen-up corner check")
    for point in machine_corners:
        header.append(
            f"G0 X{_format_number(point.x, decimals)} "
            f"Y{_format_number(point.y, decimals)} F{travel_feed}"
        )

    drawing = generate_gcode(document, machine_config).splitlines()
    drawing = [
        line
        for line in drawing
        if line not in {"; Generated by plotter-processor", "G21", "G90", "G28", "; End"}
    ]
    header.append("; Drawing test")
    header.extend(drawing)
    header.append("; End calibration")
    return "\n".join(header) + "\n"


def _validated_settings(
    document: PathDocument,
    machine_config: dict[str, Any],
) -> dict[str, Any]:
    pen = _mapping(machine_config, "pen")
    feedrate = _mapping(machine_config, "feedrate_mm_min")
    workspace = _mapping(machine_config, "workspace_mm")
    gcode = _mapping(machine_config, "gcode")
    _mapping(machine_config, "page_origin_mm")
    axes = _mapping(machine_config, "axes")

    up_z = _number(pen, "up_z_mm")
    down_z = _number(pen, "down_z_mm")
    if up_z <= down_z:
        raise ValueError("pen.up_z_mm must be greater than pen.down_z_mm")

    draw_feed = _positive_number(feedrate, "draw")
    travel_feed = _positive_number(feedrate, "travel")
    z_feed = _positive_number(feedrate, "z")
    settle_ms = pen.get("settle_ms")
    if isinstance(settle_ms, bool) or not isinstance(settle_ms, int) or settle_ms < 0:
        raise ValueError("pen.settle_ms must be a non-negative integer")

    decimals = gcode.get("decimals")
    if isinstance(decimals, bool) or not isinstance(decimals, int) or not 0 <= decimals <= 6:
        raise ValueError("gcode.decimals must be an integer between 0 and 6")
    for key in ("invert_x", "invert_y"):
        if not isinstance(axes.get(key), bool):
            raise TypeError(f"axes.{key} must be boolean")

    if not document.strokes:
        raise ValueError("Path document contains no strokes")
    for stroke in document.strokes:
        if len(stroke.points) < 2:
            raise ValueError("Each stroke must contain at least two points")
        for point in stroke.points:
            if not math.isfinite(point.x) or not math.isfinite(point.y):
                raise ValueError("All path coordinates must be finite")

    validated_workspace = {
        key: _number(workspace, key) for key in ("min_x", "max_x", "min_y", "max_y")
    }
    if (
        validated_workspace["min_x"] >= validated_workspace["max_x"]
        or validated_workspace["min_y"] >= validated_workspace["max_y"]
    ):
        raise ValueError("workspace_mm minimums must be smaller than maximums")

    return {
        "up_z": up_z,
        "down_z": down_z,
        "settle_ms": settle_ms,
        "draw_feed": draw_feed,
        "travel_feed": travel_feed,
        "z_feed": z_feed,
        "workspace": validated_workspace,
        "home": _boolean(gcode, "home"),
        "absolute_positioning": _boolean(gcode, "absolute_positioning"),
        "units_mm": _boolean(gcode, "units_mm"),
        "decimals": decimals,
    }


def _validate_workspace(points: list[Point], workspace: dict[str, float]) -> None:
    for point in points:
        if not (
            workspace["min_x"] <= point.x <= workspace["max_x"]
            and workspace["min_y"] <= point.y <= workspace["max_y"]
        ):
            raise ValueError(
                f"Machine coordinate X{point.x:.3f} Y{point.y:.3f} is outside workspace limits."
            )


def _mapping(config: dict[str, Any], key: str) -> dict[str, Any]:
    value = config.get(key)
    if not isinstance(value, dict):
        raise TypeError(f"{key} must be a mapping")
    return value


def _number(config: dict[str, Any], key: str) -> float:
    value = config.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"{key} must be a number")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"{key} must be finite")
    return number


def _positive_number(config: dict[str, Any], key: str) -> float:
    number = _number(config, key)
    if number <= 0:
        raise ValueError(f"{key} must be positive")
    return number


def _boolean(config: dict[str, Any], key: str) -> bool:
    value = config.get(key)
    if not isinstance(value, bool):
        raise TypeError(f"gcode.{key} must be boolean")
    return value


def _format_number(value: float, decimals: int) -> str:
    return f"{value:.{decimals}f}"


def _append_unique(lines: list[str], command: str) -> None:
    if not lines or lines[-1] != command:
        lines.append(command)
