from __future__ import annotations

import math
from collections.abc import Mapping

from plotter_processor.gcode_exporter import DEFAULT_MAX_GCODE_COMMANDS, transform_point
from plotter_processor.job_models import PlotterJob
from plotter_processor.models import PathDocument, Point
from plotter_processor.motion_config import ResolvedMotionProfile


def generate_job_gcode(
    job: PlotterJob,
    machine_config: dict[str, object],
    *,
    max_commands: int = DEFAULT_MAX_GCODE_COMMANDS,
    motion_profile: ResolvedMotionProfile | None = None,
) -> str:
    if not job.pages:
        raise ValueError("Plotter job contains no pages")
    if max_commands < 1:
        raise ValueError("max_commands must be positive")
    pen = _mapping(machine_config, "pen")
    feed = _mapping(machine_config, "feedrate_mm_min")
    gcode = _mapping(machine_config, "gcode")
    page_change = _mapping(machine_config, "page_change")
    decimals = _integer(gcode, "decimals")
    up_z = _format(_number(pen, "up_z_mm"), decimals)
    down_z = _format(_number(pen, "down_z_mm"), decimals)
    settle_ms = int(pen.get("settle_ms", pen.get("down_settle_ms", 0)))
    travel_feed = _format(_number(feed, "travel"), decimals)
    draw_feed = _format(_number(feed, "draw"), decimals)
    z_feed = _format(_number(feed, "z"), decimals)
    lines = ["; Generated by plotter-processor", f"; Pages: {len(job.pages)}"]
    if motion_profile is not None:
        lines.append(f"; Motion profile: {motion_profile.name}")
    if bool(gcode.get("units_mm", True)):
        lines.append("G21")
    if bool(gcode.get("absolute_positioning", True)):
        lines.append("G90")
    if bool(gcode.get("home", False)):
        lines.append("G28")
    lines.append(f"G0 Z{up_z} F{z_feed}")

    for index, page_job in enumerate(job.pages):
        number = index + 1
        lines.append(f"; ===== PAGE {number}/{len(job.pages)} START =====")
        lines.extend(_drawing_lines(
            page_job.path_document, machine_config, decimals=decimals, up_z=up_z,
            down_z=down_z, z_feed=z_feed, travel_feed=travel_feed,
            draw_feed=draw_feed, settle_ms=settle_ms,
        ))
        if index == len(job.pages) - 1:
            continue
        _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
        lines.append(f"; PAGE {number}/{len(job.pages)} COMPLETE")
        park = resolve_park_point(job, machine_config)
        lines.append(
            f"G0 X{_format(park.x, decimals)} Y{_format(park.y, decimals)} F{travel_feed}"
        )
        lines.append("M400")
        pause_seconds = _non_negative(page_change, "pause_seconds")
        lines.append(f"; CHANGE PAPER - WAIT {_format_seconds(pause_seconds)} SECONDS")
        wait_command = str(page_change.get("wait_command", "dwell"))
        if wait_command != "dwell":
            raise ValueError(f"Unsupported page_change.wait_command: {wait_command}")
        lines.append(f"G4 P{round(pause_seconds * 1000)}")

    _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
    lines.extend(("M400", "M84", "; End"))
    if len(lines) > max_commands:
        raise ValueError(
            f"G-code would contain {len(lines)} commands, exceeding the safe limit "
            f"of {max_commands}."
        )
    return "\n".join(lines) + "\n"


def resolve_park_point(job: PlotterJob, machine_config: Mapping[str, object]) -> Point:
    page_change = _mapping(machine_config, "page_change")
    park = _mapping(page_change, "park")
    mode = str(park.get("mode", "corner"))
    if mode == "machine_point":
        point = Point(_number(park, "x_mm"), _number(park, "y_mm"))
    elif mode == "corner":
        inset = _non_negative(park, "inset_mm")
        corner = str(park.get("corner", "top_right"))
        coordinates = {
            "top_left": Point(inset, inset),
            "top_right": Point(job.page_spec.width_mm - inset, inset),
            "bottom_left": Point(inset, job.page_spec.height_mm - inset),
            "bottom_right": Point(
                job.page_spec.width_mm - inset, job.page_spec.height_mm - inset
            ),
        }
        if corner not in coordinates:
            raise ValueError(f"Unknown page-change park corner: {corner}")
        sample = PathDocument(job.page_spec.width_mm, job.page_spec.height_mm, [], [])
        point = transform_point(coordinates[corner], sample, dict(machine_config))
    else:
        raise ValueError(f"Unknown page-change park mode: {mode}")
    _validate_workspace([point], _mapping(machine_config, "workspace_mm"))
    return point


def _drawing_lines(
    document: PathDocument,
    machine_config: dict[str, object],
    *,
    decimals: int,
    up_z: str,
    down_z: str,
    z_feed: str,
    travel_feed: str,
    draw_feed: str,
    settle_ms: int,
) -> list[str]:
    workspace = _mapping(machine_config, "workspace_mm")
    lines: list[str] = []
    for stroke in document.strokes:
        source_points = [stroke.points[0]]
        for point in stroke.points[1:]:
            if point != source_points[-1]:
                source_points.append(point)
        machine_points = [transform_point(point, document, machine_config) for point in source_points]
        rounded: list[Point] = []
        for point in machine_points:
            candidate = Point(round(point.x, decimals), round(point.y, decimals))
            if not rounded or candidate != rounded[-1]:
                rounded.append(candidate)
        if len(rounded) < 2:
            continue
        _validate_workspace(rounded, workspace)
        start = rounded[0]
        _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
        lines.append(
            f"G0 X{_format(start.x, decimals)} Y{_format(start.y, decimals)} F{travel_feed}"
        )
        lines.append(f"G1 Z{down_z} F{z_feed}")
        if settle_ms:
            lines.append(f"G4 P{settle_ms}")
        draw_points = list(rounded[1:])
        if stroke.closed and rounded[-1] != rounded[0]:
            draw_points.append(rounded[0])
        for point_index, point in enumerate(draw_points):
            suffix = f" F{draw_feed}" if point_index == 0 else ""
            lines.append(
                f"G1 X{_format(point.x, decimals)} Y{_format(point.y, decimals)}{suffix}"
            )
        _append_unique(lines, f"G0 Z{up_z} F{z_feed}")
    return lines


def _validate_workspace(points: list[Point], workspace: Mapping[str, object]) -> None:
    minimum_x = _number(workspace, "min_x")
    maximum_x = _number(workspace, "max_x")
    minimum_y = _number(workspace, "min_y")
    maximum_y = _number(workspace, "max_y")
    for point in points:
        if not (minimum_x <= point.x <= maximum_x and minimum_y <= point.y <= maximum_y):
            raise ValueError(
                f"Machine coordinate X{point.x:.3f} Y{point.y:.3f} is outside workspace limits."
            )


def _append_unique(lines: list[str], command: str) -> None:
    if not lines or lines[-1] != command:
        lines.append(command)


def _mapping(values: Mapping[str, object], key: str) -> Mapping[str, object]:
    value = values.get(key)
    if not isinstance(value, Mapping):
        raise TypeError(f"Missing or invalid mapping field: {key}")
    return value


def _number(values: Mapping[str, object], key: str) -> float:
    value = values.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"Missing or invalid finite field: {key}")
    return float(value)


def _non_negative(values: Mapping[str, object], key: str) -> float:
    value = _number(values, key)
    if value < 0:
        raise ValueError(f"Missing or invalid non-negative field: {key}")
    return value


def _integer(values: Mapping[str, object], key: str) -> int:
    value = values.get(key)
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise ValueError(f"Missing or invalid integer field: {key}")
    return value


def _format(value: float, decimals: int) -> str:
    return f"{value:.{decimals}f}".rstrip("0").rstrip(".") or "0"


def _format_seconds(value: float) -> str:
    return str(int(value)) if value.is_integer() else str(value)
