DOCUMENT_MODEL_SCHEMA_VERSION = 1
LAYOUT_MODEL_SCHEMA_VERSION = 1
PATHS_SCHEMA_VERSION = 2
STAGE_CACHE_SCHEMA_VERSION = 2
COMPILED_FONT_SCHEMA_VERSION = 3
JOB_SCHEMA_VERSION = 1
BUILD_REPORT_SCHEMA_VERSION = 1


SCHEMA_VERSIONS = {
    "document_model": DOCUMENT_MODEL_SCHEMA_VERSION,
    "layout_model": LAYOUT_MODEL_SCHEMA_VERSION,
    "paths": PATHS_SCHEMA_VERSION,
    "stage_cache": STAGE_CACHE_SCHEMA_VERSION,
    "compiled_font": COMPILED_FONT_SCHEMA_VERSION,
    "job": JOB_SCHEMA_VERSION,
    "build_report": BUILD_REPORT_SCHEMA_VERSION,
}
