#include "plotter/doc/gcode_exporter.hpp"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <array>
#include <charconv>
#include <fstream>
#include <iomanip>
#include <locale>
#include <sstream>
#include <stdexcept>
#include <vector>

namespace plotter::doc {
namespace {

std::string fixed(double value, std::uint32_t decimals) {
    std::array<char, 128> buffer{};
    const auto [end, error] = std::to_chars(buffer.data(), buffer.data() + buffer.size(),
                                            value, std::chars_format::fixed,
                                            static_cast<int>(decimals));
    if (error != std::errc{}) throw std::invalid_argument("Cannot format G-code coordinate");
    return {buffer.data(), end};
}

double rounded(double value, std::uint32_t decimals) {
    const double factor = std::pow(10.0, static_cast<double>(decimals));
    return std::nearbyint(value * factor) / factor;
}

bool same(Point left, Point right) {
    return left.x.value == right.x.value && left.y.value == right.y.value;
}

// The feed of a segment is limited by the sharper turn at either end.
// Endpoint turns are ignored on open strokes; the controller handles stopping there.
double turn_cosine(const std::vector<Point>& points, std::size_t vertex, bool closed) {
    const std::size_t count = points.size();
    if (!closed && (vertex == 0 || vertex + 1 == count)) return 1.0;
    const Point before = points[(vertex + count - 1) % count];
    const Point here = points[vertex];
    const Point after = points[(vertex + 1) % count];
    const double ax = here.x.value - before.x.value;
    const double ay = here.y.value - before.y.value;
    const double bx = after.x.value - here.x.value;
    const double by = after.y.value - here.y.value;
    const double lengths = std::hypot(ax, ay) * std::hypot(bx, by);
    return lengths > 0.0 ? (ax * bx + ay * by) / lengths : 1.0;
}

void append_unique(std::vector<std::string>& lines, const std::string& line) {
    if (lines.empty() || lines.back() != line) lines.push_back(line);
}

void ensure_workspace(Point point, const WorkspaceConfig& workspace) {
    if (point.x.value < workspace.min_x.value || point.x.value > workspace.max_x.value ||
        point.y.value < workspace.min_y.value || point.y.value > workspace.max_y.value) {
        throw std::invalid_argument("Machine point is outside workspace");
    }
}

void ensure_preflight(const PathDocument& document, const MachineConfig& machine) {
    PipelineConfig config;
    config.page.width = document.page_width;
    config.page.height = document.page_height;
    config.machine = machine;
    for (const auto& issue : preflight(document, config).issues) {
        if (issue.severity == PreflightSeverity::error) {
            throw std::invalid_argument(issue.code + ": " + issue.message);
        }
    }
}

}  // namespace

Point to_machine_point(Point point, const PathDocument& document,
                       const MachineConfig& machine) {
    if (machine.invert_x) point.x = document.page_width - point.x;
    if (machine.invert_y) point.y = document.page_height - point.y;
    return {machine.page_origin.x + point.x, machine.page_origin.y + point.y};
}

std::string generate_gcode(const PathDocument& document, const MachineConfig& machine,
                           std::size_t max_commands) {
    if (max_commands == 0) throw std::invalid_argument("max_commands must be positive");
    ensure_preflight(document, machine);
    const auto decimals = machine.gcode.decimals;
    const std::string up = fixed(machine.pen.up_z.value, decimals);
    const std::string down = fixed(machine.pen.down_z.value, decimals);
    const std::string z_feed = fixed(machine.feedrate.z_mm_min, decimals);
    const std::string travel_feed = fixed(machine.feedrate.travel_mm_min, decimals);
    const std::string draw_feed = fixed(machine.feedrate.tight_mm_min, decimals);
    const std::string draw_mid_feed = fixed(machine.feedrate.curve_mm_min, decimals);
    const std::string draw_fast_feed = fixed(machine.feedrate.draw_fast_mm_min, decimals);
    const std::string pen_up = "G0 Z" + up + " F" + z_feed;
    std::vector<std::string> lines{"; Generated by plotter-processor"};
    if (machine.gcode.units_mm) lines.emplace_back("G21");
    if (machine.gcode.absolute_positioning) lines.emplace_back("G90");
    if (machine.gcode.home) lines.emplace_back("G28");
    lines.push_back(pen_up);

    for (const auto& stroke : document.strokes) {
        std::vector<Point> points;
        points.reserve(stroke.points.size());
        for (const Point source : stroke.points) {
            if (!points.empty() && same(source, points.back())) continue;
            points.push_back(source);
        }
        std::vector<Point> machine_points;
        machine_points.reserve(points.size());
        for (const Point source : points) {
            const Point transformed = to_machine_point(source, document, machine);
            const Point point{{rounded(transformed.x.value, decimals)},
                              {rounded(transformed.y.value, decimals)}};
            if (!machine_points.empty() && same(point, machine_points.back())) continue;
            ensure_workspace(point, machine.workspace);
            machine_points.push_back(point);
        }
        if (machine_points.size() < 2) continue;
        const Point start = machine_points.front();
        append_unique(lines, pen_up);
        lines.push_back("G0 X" + fixed(start.x.value, decimals) + " Y" +
                        fixed(start.y.value, decimals) + " F" + travel_feed);
        lines.push_back("G1 Z" + down + " F" + z_feed);
        if (machine.pen.down_settle_ms > 0)
            lines.push_back("G4 P" + std::to_string(machine.pen.down_settle_ms));
        const bool close_stroke = stroke.closed && !same(machine_points.back(), start);
        const std::size_t segment_count = machine_points.size() - 1 + (close_stroke ? 1 : 0);
        std::string previous_feed;
        for (std::size_t index = 1; index <= segment_count; ++index) {
            const std::size_t from = index - 1;
            const std::size_t to = index % machine_points.size();
            const Point point = machine_points[to];
            const double cosine = std::min(turn_cosine(machine_points, from, close_stroke),
                                           turn_cosine(machine_points, to, close_stroke));
            const std::string& feed = cosine < machine.feedrate.curvature_threshold_2 ? draw_feed
                                    : cosine < machine.feedrate.curvature_threshold_1 ? draw_mid_feed : draw_fast_feed;
            lines.push_back("G1 X" + fixed(point.x.value, decimals) + " Y" +
                            fixed(point.y.value, decimals) +
                            (feed != previous_feed ? " F" + feed : ""));
            previous_feed = feed;
        }
        append_unique(lines, pen_up);
        if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    }
    append_unique(lines, pen_up);
    lines.emplace_back("M400");
    lines.emplace_back("M84");
    lines.emplace_back("; End");
    if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    std::size_t byte_count = 0;
    for (const auto& line : lines) byte_count += line.size() + 1;
    std::string output;
    output.reserve(byte_count);
    for (const auto& line : lines) { output += line; output += '\n'; }
    return output;
}

void write_gcode_atomic(const std::string& gcode, const std::filesystem::path& output) {
    if (!output.parent_path().empty())
        std::filesystem::create_directories(output.parent_path());
    auto temporary = output;
    temporary += "." + std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()) + ".tmp";
    try {
        {
            std::ofstream stream(temporary, std::ios::binary | std::ios::trunc);
            if (!stream) throw std::runtime_error("Cannot create temporary G-code file");
            stream.write(gcode.data(), static_cast<std::streamsize>(gcode.size()));
            stream.flush();
            if (!stream) throw std::runtime_error("Cannot write temporary G-code file");
        }
        std::filesystem::rename(temporary, output);
    } catch (...) {
        std::error_code ignored;
        std::filesystem::remove(temporary, ignored);
        throw;
    }
}

}  // namespace plotter::doc
