#include "plotter/doc/multipage_gcode_exporter.hpp"

#include <cmath>
#include <array>
#include <charconv>
#include <iomanip>
#include <locale>
#include <sstream>
#include <stdexcept>
#include <vector>

namespace plotter::doc {
namespace {

std::string fixed(double value, std::uint32_t decimals) {
    std::array<char, 128> buffer{};
    const auto [end, error] = std::to_chars(buffer.data(), buffer.data() + buffer.size(),
                                            value, std::chars_format::fixed,
                                            static_cast<int>(decimals));
    if (error != std::errc{}) throw std::invalid_argument("Cannot format G-code coordinate");
    return {buffer.data(), end};
}

std::string seconds_text(double value) {
    std::ostringstream stream;
    stream.imbue(std::locale::classic());
    stream << std::setprecision(12) << value;
    return stream.str();
}

void append_unique(std::vector<std::string>& lines, const std::string& line) {
    if (lines.empty() || lines.back() != line) lines.push_back(line);
}

void ensure_workspace(Point point, const WorkspaceConfig& workspace) {
    if (point.x.value < workspace.min_x.value || point.x.value > workspace.max_x.value ||
        point.y.value < workspace.min_y.value || point.y.value > workspace.max_y.value)
        throw std::invalid_argument("Page-change park point is outside workspace");
}

Point park_point(const PlotterJob& job, const MachineConfig& machine) {
    const auto& park = machine.page_change;
    if (park.park_mode == "machine_point") {
        ensure_workspace(park.park_machine_point, machine.workspace);
        return park.park_machine_point;
    }
    if (park.park_mode != "corner" || park.park_inset.value < 0.0)
        throw std::invalid_argument("Invalid page-change park mode or inset");
    const auto inset = park.park_inset;
    Point page{};
    if (park.park_corner == "top_left") page = {inset, inset};
    else if (park.park_corner == "top_right") page = {job.page_width - inset, inset};
    else if (park.park_corner == "bottom_left") page = {inset, job.page_height - inset};
    else if (park.park_corner == "bottom_right")
        page = {job.page_width - inset, job.page_height - inset};
    else throw std::invalid_argument("Invalid page-change park corner");
    PathDocument geometry;
    geometry.page_width = job.page_width;
    geometry.page_height = job.page_height;
    const Point machine_point = to_machine_point(page, geometry, machine);
    ensure_workspace(machine_point, machine.workspace);
    return machine_point;
}

std::vector<std::string> drawing_lines(const PathDocument& paths, const MachineConfig& machine) {
    const std::string single = generate_gcode(paths, machine);
    std::istringstream input(single);
    std::string line;
    std::vector<std::string> all;
    while (std::getline(input, line)) all.push_back(std::move(line));
    std::size_t first = 1;
    while (first < all.size() &&
           (all[first] == "G21" || all[first] == "G90" || all[first] == "G28")) ++first;
    if (first < all.size()) ++first; // The per-page initial pen-up belongs to the job header.
    if (all.size() < first + 3) throw std::runtime_error("Invalid single-page G-code body");
    return {all.begin() + static_cast<std::ptrdiff_t>(first), all.end() - 3};
}

}  // namespace

std::string generate_job_gcode(const PlotterJob& job, const MachineConfig& machine,
                               std::size_t max_commands) {
    if (job.pages.empty()) throw std::invalid_argument("Plotter job contains no pages");
    if (max_commands == 0) throw std::invalid_argument("max_commands must be positive");
    if (job.page_width.value <= 0.0 || job.page_height.value <= 0.0)
        throw std::invalid_argument("Plotter job page size must be positive");
    const auto decimals = machine.gcode.decimals;
    const std::string pen_up = "G0 Z" + fixed(machine.pen.up_z.value, decimals) +
                               " F" + fixed(machine.feedrate.z_mm_min, decimals);
    const std::string travel_feed = fixed(machine.feedrate.travel_mm_min, decimals);
    std::vector<std::string> lines{"; Generated by plotter-processor",
                                   "; Pages: " + std::to_string(job.pages.size())};
    if (machine.gcode.units_mm) lines.emplace_back("G21");
    if (machine.gcode.absolute_positioning) lines.emplace_back("G90");
    if (machine.gcode.home) lines.emplace_back("G28");
    lines.push_back(pen_up);
    for (std::size_t index = 0; index < job.pages.size(); ++index) {
        const auto& page = job.pages[index];
        if (page.paths.page_width.value != job.page_width.value ||
            page.paths.page_height.value != job.page_height.value)
            throw std::invalid_argument("Page geometry differs from job page size");
        const std::string label = std::to_string(index + 1) + "/" +
                                  std::to_string(job.pages.size());
        lines.push_back("; ===== PAGE " + label + " START =====");
        lines.push_back(pen_up);
        const auto drawing = drawing_lines(page.paths, machine);
        lines.insert(lines.end(), drawing.begin(), drawing.end());
        if (index + 1 == job.pages.size()) continue;
        if (!machine.page_change.enabled)
            throw std::invalid_argument("Multi-page output needs page-change behavior");
        if (machine.page_change.wait_command != "dwell" ||
            !std::isfinite(machine.page_change.pause_seconds) ||
            machine.page_change.pause_seconds < 0.0)
            throw std::invalid_argument("Invalid page-change wait behavior");
        append_unique(lines, pen_up);
        lines.push_back("; PAGE " + label + " COMPLETE");
        const Point park = park_point(job, machine);
        lines.push_back("G0 X" + fixed(park.x.value, decimals) + " Y" +
                        fixed(park.y.value, decimals) + " F" + travel_feed);
        lines.emplace_back("M400");
        lines.push_back("; CHANGE PAPER - WAIT " +
                        seconds_text(machine.page_change.pause_seconds) + " SECONDS");
        lines.push_back("G4 P" + std::to_string(static_cast<long long>(
            std::nearbyint(machine.page_change.pause_seconds * 1000.0))));
        if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    }
    append_unique(lines, pen_up);
    lines.emplace_back("M400");
    lines.emplace_back("M84");
    lines.emplace_back("; End");
    if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    std::size_t byte_count = 0;
    for (const auto& line : lines) byte_count += line.size() + 1;
    std::string output;
    output.reserve(byte_count);
    for (const auto& line : lines) { output += line; output += '\n'; }
    return output;
}

}  // namespace plotter::doc
