#include "plotter/doc/gcode_exporter.hpp"

#include <chrono>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <locale>
#include <sstream>
#include <stdexcept>
#include <vector>

namespace plotter::doc {
namespace {

std::string fixed(double value, std::uint32_t decimals) {
    std::ostringstream out;
    out.imbue(std::locale::classic());
    out << std::fixed << std::setprecision(static_cast<int>(decimals)) << value;
    return out.str();
}

double rounded(double value, std::uint32_t decimals) {
    const double factor = std::pow(10.0, static_cast<double>(decimals));
    return std::nearbyint(value * factor) / factor;
}

bool same(Point left, Point right) {
    return left.x.value == right.x.value && left.y.value == right.y.value;
}

void append_unique(std::vector<std::string>& lines, const std::string& line) {
    if (lines.empty() || lines.back() != line) lines.push_back(line);
}

void ensure_workspace(Point point, const WorkspaceConfig& workspace) {
    if (point.x.value < workspace.min_x.value || point.x.value > workspace.max_x.value ||
        point.y.value < workspace.min_y.value || point.y.value > workspace.max_y.value) {
        throw std::invalid_argument("Machine point is outside workspace");
    }
}

void ensure_preflight(const PathDocument& document, const MachineConfig& machine) {
    PipelineConfig config;
    config.page.width = document.page_width;
    config.page.height = document.page_height;
    config.machine = machine;
    for (const auto& issue : preflight(document, config).issues) {
        if (issue.severity == PreflightSeverity::error) {
            throw std::invalid_argument(issue.code + ": " + issue.message);
        }
    }
}

}  // namespace

Point to_machine_point(Point point, const PathDocument& document,
                       const MachineConfig& machine) {
    if (machine.invert_x) point.x = document.page_width - point.x;
    if (machine.invert_y) point.y = document.page_height - point.y;
    return {machine.page_origin.x + point.x, machine.page_origin.y + point.y};
}

std::string generate_gcode(const PathDocument& document, const MachineConfig& machine,
                           std::size_t max_commands) {
    if (max_commands == 0) throw std::invalid_argument("max_commands must be positive");
    ensure_preflight(document, machine);
    const auto decimals = machine.gcode.decimals;
    const std::string up = fixed(machine.pen.up_z.value, decimals);
    const std::string down = fixed(machine.pen.down_z.value, decimals);
    const std::string z_feed = fixed(machine.feedrate.z_mm_min, decimals);
    const std::string travel_feed = fixed(machine.feedrate.travel_mm_min, decimals);
    const std::string draw_feed = fixed(machine.feedrate.draw_mm_min, decimals);
    const std::string pen_up = "G0 Z" + up + " F" + z_feed;
    std::vector<std::string> lines{"; Generated by plotter-processor"};
    if (machine.gcode.units_mm) lines.emplace_back("G21");
    if (machine.gcode.absolute_positioning) lines.emplace_back("G90");
    if (machine.gcode.home) lines.emplace_back("G28");
    lines.push_back(pen_up);

    for (const auto& stroke : document.strokes) {
        std::vector<Point> points;
        points.reserve(stroke.points.size());
        for (const Point source : stroke.points) {
            if (!points.empty() && same(source, points.back())) continue;
            points.push_back(source);
        }
        std::vector<Point> machine_points;
        machine_points.reserve(points.size());
        for (const Point source : points) {
            const Point transformed = to_machine_point(source, document, machine);
            const Point point{{rounded(transformed.x.value, decimals)},
                              {rounded(transformed.y.value, decimals)}};
            if (!machine_points.empty() && same(point, machine_points.back())) continue;
            ensure_workspace(point, machine.workspace);
            machine_points.push_back(point);
        }
        if (machine_points.size() < 2) continue;
        const Point start = machine_points.front();
        append_unique(lines, pen_up);
        lines.push_back("G0 X" + fixed(start.x.value, decimals) + " Y" +
                        fixed(start.y.value, decimals) + " F" + travel_feed);
        lines.push_back("G1 Z" + down + " F" + z_feed);
        if (machine.pen.down_settle_ms > 0)
            lines.push_back("G4 P" + std::to_string(machine.pen.down_settle_ms));
        std::size_t draw_index = 0;
        for (std::size_t index = 1; index < machine_points.size(); ++index) {
            const Point point = machine_points[index];
            lines.push_back("G1 X" + fixed(point.x.value, decimals) + " Y" +
                            fixed(point.y.value, decimals) +
                            (draw_index++ == 0 ? " F" + draw_feed : ""));
        }
        if (stroke.closed && !same(machine_points.back(), start)) {
            lines.push_back("G1 X" + fixed(start.x.value, decimals) + " Y" +
                            fixed(start.y.value, decimals));
        }
        append_unique(lines, pen_up);
        if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    }
    append_unique(lines, pen_up);
    lines.emplace_back("M400");
    lines.emplace_back("M84");
    lines.emplace_back("; End");
    if (lines.size() > max_commands) throw std::length_error("G-code command limit exceeded");
    std::string output;
    for (const auto& line : lines) { output += line; output += '\n'; }
    return output;
}

void write_gcode_atomic(const std::string& gcode, const std::filesystem::path& output) {
    if (!output.parent_path().empty())
        std::filesystem::create_directories(output.parent_path());
    auto temporary = output;
    temporary += "." + std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()) + ".tmp";
    try {
        {
            std::ofstream stream(temporary, std::ios::binary | std::ios::trunc);
            if (!stream) throw std::runtime_error("Cannot create temporary G-code file");
            stream.write(gcode.data(), static_cast<std::streamsize>(gcode.size()));
            stream.flush();
            if (!stream) throw std::runtime_error("Cannot write temporary G-code file");
        }
        std::filesystem::rename(temporary, output);
    } catch (...) {
        std::error_code ignored;
        std::filesystem::remove(temporary, ignored);
        throw;
    }
}

}  // namespace plotter::doc
